### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by vitlav** [Etersoft/libnss-role#6]
Please, click the button „Draft new release” on the releases page to fill a form described new release. We have to do it every time another release is ready.
See 0.4.0 version for an example.

**Comment by ghost** [comment]
The upcoming PR #26 introduces new feature along with test improvements. Also numerous bugs were found and we must decide if we fix them before the release or after. It is also needed to mention that there were many breaking changes so, possibly, it is needed to increase major version.

**Comment by ghost** [comment]
Ping @vitlav , @mastersin .
