### ISSUE TITLE
Missing license headers in source files

### ISSUE THREAD

**Issue by ghost** [Etersoft/libnss-role#9]
It is impossible to present the project to the audience unless we include copyright headers. Personally, I think that it will be nice to dual-license the project under BSD too (at least, on request), so BSD/Illumos/etc OSes will be able to include the library into base distribution.

**Comment by vitlav** [comment]
Есть подозрение, что библиотека завязана на glibc, поэтому вопрос перелицензирования я бы отложил до момента, когда библиотека заработает на одной из упомянутых систем.
Заголовки про лицензии надо добавить...

**Comment by vitlav** [comment]
Предлагаю согласовать заголовок с копирайтами.

```
/*
    Copyright (c) 2008-2020 Etersoft
    Copyright (c) 2020 BaseALT

    NSS library for roles and privileges.

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation, version 2.1
    of the License.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
    USA.
*/
```

**Comment by ghost** [comment]
@vitlav , с нашей стороны - принимаем. :) Надо делать pull request и тогда анонсировать. Можно ещё на помойках типа LOR и opennet написать.

**Comment by ghost** [comment]
https://github.com/Etersoft/libnss-role/pull/10
